- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - apache2
    - apache2-doc
    - apache2-utils
    - libapache2-mod-php

- name: Enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - rewrite
    - headers

- name: Disable sites
  command: a2dissite 000-default

- name: Enable sites
  command: a2ensite default-ssl

- name: Generate DH key
  stat:
    path: /etc/ssl/private/dhparam.pem
  register: stat_dhparam
- shell: openssl dhparam -out /etc/ssl/private/dhparam.pem 2048
  when: stat_dhparam.stat.exists == False
- shell: openssl req -new -nodes -x509 -days 3650 -subj "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_local }}/O={{ cert_org }}/CN={{ servername }}" -keyout /etc/ssl/private/misp.key -out /etc/ssl/private/misp.crt
  when: stat_dhparam.stat.exists == False

- name: Get config file
  template:
    src: templates/apache/misp-ssl.conf
    dest: /etc/apache2/sites-available/misp-ssl.conf

- name: Get config file
  template:
    src: templates/apache/default-ssl.conf
    dest: /etc/apache2/sites-available/default-ssl.conf

- name: Disable sites
  command: a2dissite default-ssl

- name: Enable sites
  command: a2ensite misp-ssl

- name: Restart Apache
  service:
    name: apache2
    state: restarted
